name: Publish Docker Image to GHCR

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release
      - dev
    tags:
      - 'v*.*.*' # Semantic versioning pattern

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/eed-solutions/eed_docker_python_uv
          TAG=latest

          # Determine tag based on context
                    if [[ "${{ github.ref_type }}" == "branch" ]]; then
            case "${{ github.ref_name }}" in
              "main")
                TAG=main
                ;;
              "dev")
                TAG=dev
                ;;
              "release")
                TAG=release
                ;;
              *)
                TAG=${{ github.ref_name }}
                ;;
            esac
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            # For tags, use the tag name (should be semantic version like v1.0.0)
            TAG=${{ github.ref_name }}
          else
            # Fallback
            TAG=latest
          fi
          # Build and push the image
          docker build -t $IMAGE_NAME:$TAG -f .devcontainer/Dockerfile .
          docker push $IMAGE_NAME:$TAG

          # Push additional 'latest' tag for semantic version tags
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
            docker push $IMAGE_NAME:latest
          fi
