name: Publish Docker Image to GHCR

on:
  workflow_dispatch:
#   push:
#     branches: [main]
#     paths:
#       - '.devcontainer/Dockerfile'
#       - '.github/workflows/publish.yml'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/eed-solutions/eed_docker_python_uv:latest
          docker build -t $IMAGE_NAME -f .devcontainer/Dockerfile .
          docker push $IMAGE_NAME
